### PR TITLE
Evaluate com ports using pyserial

### PR DESCRIPTION
**Pull request by IanCassTwo**
Thanks for creating this. Just yesterday I had a requirement to log some data on my N56FU and of course the original software no longer works, good luck compiling QtDMM2, and Sigrok doesn't support it, so I'd resigned myself to writing something until I found this. I work with both Linux and Windows so I needed this code to be able to connect to devices on both. Seems PySerial already has this covered. This PR (hopefully) allows this to work on both Linux & Windows. I've tested on Ubuntu and on Windows 10.

### CODE REVIEW

**Comment by BrianSwatton** [comment]
Hi Ian, thanks for the contribution.  I'm currently working out how to deal with pull requests and reviewing code, I'm a github noob.  Windows capability is a very useful addition, thanks. I haven't touched a windows machine in a decade, but now have a laptop that will boot to it.  I'll get python going on it and try it there too.

**Comment by BrianSwatton** [comment]
It tested fine on Linux, but I can't get it to work on windows 10 on my Lenovo ThinkPad.  It runs but reports "No meter found.", because serial.tools.list_ports.comports() always returns an empty list.   It works on Ubuntu on the same machine.  I lack much experience of windows OS in the last 10years, but did try as administrator too.

**Comment by IanCassTwo** [comment]
I guess the good thing is that it still works on Linux & there's no regression. For Windows, did you look in device manager to see if it's recognised it? To get there, right click the windows icon at bottom left and choose "device manager". You should see it beneath the "Ports (COM & LPT)" entry.

**Comment by IanCassTwo** [comment]
Also, if it helps, I found my original CD and uploaded the Windows app here https://archive.org/details/N56FU. It still works on Windows 10 after all, provided the com port number is low. I didn't test exactly what the limitation is, but it didn't work when my com port was COM14 but did when I set it to COM3.

**Comment by BrianSwatton** [comment]
Ah. Not as a com port, but as the CP2102 USB to UART Bridge - without a  driver, so that would explain that.  It couldn't find a driver on the machine.  I'll have to leave this for now. I'll investigate further.

**Comment by BrianSwatton** [comment]
I'll check that out, thanks. That will have the driver I presume.

**Comment by IanCassTwo** [comment]
You can download the driver from Silabs website. https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers?tab=downloads. I didn't upload the driver to Archive.org because the packaged one was for WinNT or Win98! I figure they would be a little out of date :D

**Comment by BrianSwatton** [comment]
Thanks for your help and patience, that is working now with the driver from your link.   I intend to merge your contribution, and will update the comments and readme. (I presume I do that with another commit after merge?)  I'm minded to acknowledge your contribution in the comments, are you ok with that?

**Comment by IanCassTwo** [comment]
I'm ok with you acknowledging but it's not really necessary to do it explicitly. Github will show me as a contributor anyway.

**Comment by BrianSwatton** [comment]
Ok, thanks for the info.

**Comment by BrianSwatton** [comment]
Now works with Windows (if CP2102 driver installed), thanks to Ian Cass.

**Pull request merged**
